"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.onMessageCreate = exports.sendAnnouncement = exports.createConversation = exports.publishPerformanceReport = exports.generateSessionDates = exports.assignTeacherToClass = exports.unenrollStudent = exports.enrollStudent = exports.onAttendanceWrite = exports.changeMyPassword = exports.requestStudentPasswordReset = exports.adminResetStudentPassword = exports.setUserStatus = exports.setUserRole = exports.createStaffUser = exports.onRegistrationCreated = exports.rejectRegistration = exports.approveRegistration = void 0;
const app_1 = require("firebase-admin/app");
const v2_1 = require("firebase-functions/v2");
(0, app_1.initializeApp)();
// Keep a lid on cost: this is a weekend school, not a high-traffic service.
(0, v2_1.setGlobalOptions)({ region: 'us-central1', maxInstances: 10 });
var registrations_1 = require("./registrations");
Object.defineProperty(exports, "approveRegistration", { enumerable: true, get: function () { return registrations_1.approveRegistration; } });
Object.defineProperty(exports, "rejectRegistration", { enumerable: true, get: function () { return registrations_1.rejectRegistration; } });
Object.defineProperty(exports, "onRegistrationCreated", { enumerable: true, get: function () { return registrations_1.onRegistrationCreated; } });
var users_1 = require("./users");
Object.defineProperty(exports, "createStaffUser", { enumerable: true, get: function () { return users_1.createStaffUser; } });
Object.defineProperty(exports, "setUserRole", { enumerable: true, get: function () { return users_1.setUserRole; } });
Object.defineProperty(exports, "setUserStatus", { enumerable: true, get: function () { return users_1.setUserStatus; } });
Object.defineProperty(exports, "adminResetStudentPassword", { enumerable: true, get: function () { return users_1.adminResetStudentPassword; } });
Object.defineProperty(exports, "requestStudentPasswordReset", { enumerable: true, get: function () { return users_1.requestStudentPasswordReset; } });
Object.defineProperty(exports, "changeMyPassword", { enumerable: true, get: function () { return users_1.changeMyPassword; } });
var attendance_1 = require("./attendance");
Object.defineProperty(exports, "onAttendanceWrite", { enumerable: true, get: function () { return attendance_1.onAttendanceWrite; } });
var school_1 = require("./school");
Object.defineProperty(exports, "enrollStudent", { enumerable: true, get: function () { return school_1.enrollStudent; } });
Object.defineProperty(exports, "unenrollStudent", { enumerable: true, get: function () { return school_1.unenrollStudent; } });
Object.defineProperty(exports, "assignTeacherToClass", { enumerable: true, get: function () { return school_1.assignTeacherToClass; } });
Object.defineProperty(exports, "generateSessionDates", { enumerable: true, get: function () { return school_1.generateSessionDates; } });
Object.defineProperty(exports, "publishPerformanceReport", { enumerable: true, get: function () { return school_1.publishPerformanceReport; } });
Object.defineProperty(exports, "createConversation", { enumerable: true, get: function () { return school_1.createConversation; } });
Object.defineProperty(exports, "sendAnnouncement", { enumerable: true, get: function () { return school_1.sendAnnouncement; } });
Object.defineProperty(exports, "onMessageCreate", { enumerable: true, get: function () { return school_1.onMessageCreate; } });
//# sourceMappingURL=index.js.map